name: 🚀 Feature request
description: Suggest a new feature or idea for this project 💡
labels: ["feature"]
assignees:
  - Julynx
body:
  - type: checkboxes
    id: self-check
    attributes:
      label: Self Check
      options:
        - label: I have searched for similar feature requests in existing GitHub Issues.
          required: true
        - label: I have checked the documentation and confirmed this feature does not already exist.
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: >
        A clear and brief description of the feature in one or two sentences.
        If you know of any real-world examples, like programs or tools that already
        have this feature, please mention them here.
      placeholder: Add support for rendering PlantUML diagrams in Markdown files. Pandoc and Typora already support this.

  - type: textarea
    id: use-case
    validations:
      required: true
    attributes:
      label: Use Case
      description: Describe how you would use this feature and what problem it solves.
      placeholder: |
        I am writing technical documentation that includes PlantUML diagrams.
        Currently, I have to render them separately and embed them as images.
        With this feature, I could write the diagram inline and have it rendered automatically.

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have a specific idea for how this could work, describe it here.
      placeholder: |
        A new code block type (e.g. ```plantuml) that gets rendered to SVG during conversion,
        similar to how Mermaid diagrams are currently handled.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Workarounds or alternative approaches you have tried or considered.
      placeholder: I currently render diagrams externally and embed them as PNG images, but this is tedious.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references. Link similar features in other projects if applicable.
